/**
 * https://leetcode.com/problems/find-the-difference/
 * You are given two strings s and t.

	String t is generated by random shuffling string s and 
	then add one more letter at a random position.
	
	Return the letter that was added to t.
 */
package solutions;

public class FindTheDifference {
	public char findTheDifference(String s, String t) {
		int sum = 0;
		int i = 0;
		while (i < s.length()) {
			sum += t.charAt(i) - s.charAt(i);
			i++;
		}
		sum += t.charAt(i);
		return (char) sum;
	}

	public static void main(String[] args) {
		System.out.println(new FindTheDifference()
			.findTheDifference("abcd", "adbca"));
	}

}
